server:
  port: 8031
spring:
  webaccess:
    #    host: http://112.216.32.4/WaWebService/Json/
    host: http://localhost:8031/WaWebService/Json/
    project: BOM
    node: BOM
  batch:
    initialize-schema=always:
  application:
    name: scheduler
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.216.32.4:3721/ing?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    jdbc-url: jdbc:mariadb://ACEMS:3721/tagdata?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: vetec3721
    initialization-mode:
      - always
    platform: maria

  jpa:
    hibernate:
      ddl-auto: none # none, create, create-drop
      use_aql_comments: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: false

mybatis:
  type-aliases-package: com.markcha.ems.mapper
  mapper-locations: mybatis/mapper/**/*.xml

response:
  jpa:
    DB_INSERT_MSG: 122#successfully created!
    DB_UPDATE_MSG: successfully saved!
    DB_DELETE_MSG: successfully deleted!
    DB_ERROR_MSG: An unexpected error occurred.
#logging.level:
#  org:
#    hibernate:
#      SQL: debug
#      type: trace


